### ISSUE TITLE
Problems generating code with pure virtual methods

### ISSUE THREAD

**Issue by emoon** [rust-qt/cpp_to_rust#1]
When generating code for qt_gui

```
qt/cpp_to_rust/gui/c_lib/source/src/qt_gui_c_QSyntaxHighlighter.cpp:4:15: error: allocating an object of abstract class type 'QSyntaxHighlighter'
  new(output) QSyntaxHighlighter(parent);
```

This is when generating code for Qt 5.7 on Mac (using the travis branch)

**Comment by Riateche** [comment]
Did you use `-d` flag to specify QtCore dependency? It will not work without `-d` because `QSyntaxHighlighter`'s pure virtual function uses `QString` and `QString` is declared in QtCore, so the function will be skipped and the generator will not know that it's an abstract class.

[This commit](https://github.com/rust-qt/cpp_to_rust/commit/a37b35d7f114d8ae3986ac59a5c4a9044c918509) seems to fix OSX support and passes on Travis. You can try to run `tests/travis.bash` on your local machine.

**Comment by emoon** [comment]
Ah. I didn't use the `-d` flag no. What is the exact command line I should use? I will try out the travis script. Thanks!

**Comment by Riateche** [comment]
Generator commands should be like that:

```
cargo run -- -s $REPOS/qt_core -o $OUT/qt_core
cargo run -- -s $REPOS/qt_gui -o $OUT/qt_gui -d $OUT/qt_core
cargo run -- -s $REPOS/qt_widgets -o $OUT/qt_widgets -d $OUT/qt_core $OUT/qt_gui

```

Does `/Users/danielcollin/clang-3.8/lib/clang/3.8.0/include` dir exist? Does it contain `stddef.h`?

**Comment by emoon** [comment]
Yeah, it's there. Maybe the issues is that '-isystem' is used instead of '-I' ?

**Comment by Riateche** [comment]
IIRC, it didn't work for me until I replaced `-I` with `-isystem`. You can tweak it at `src/cpp_parser.rs:143` and see what happens. Also try to check if `libclang` from the same directory is used and not some system-wide installation.

I don't fully understand why these headers are not visible by default. They are visible to `clang` binary, but not `libclang` for some reason. I found that this issue is mentioned a lot, but I didn't find any canonical solution.

**Comment by emoon** [comment]
Setting `-I` make it work. I now run into

```
/Users/danielcollin/Qt5.7.0/lib/QtCore.framework/Headers/qsystemdetection.h:95:12: fatal error: 'TargetConditionals.h' file not found
```

TargetConditionals.h seems to be some Mac specific header in the sdk that can be found

```
MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/TargetConditionals.h
```

I'm unsure how the script can pick up that path though.

**Comment by Riateche** [comment]
On my system Qt Creator shows that it uses `TargetConditionals.h` from `/usr/include` directory. Try to add `-I /usr/include`.

**Comment by emoon** [comment]
Hum.. I don't even have have `/usr/include` dir on my system.

**Comment by Riateche** [comment]
I've found this: http://superuser.com/a/1014872/40045
It seems that you have XCode without command line developer tools, while I have command line developer tools without XCode. Maybe you can install these tools and it will start working. I'm totally unfamiliar with OS X ecosystem, so I'm not sure if it has any drawbacks.

**Comment by emoon** [comment]
Will try!

**Comment by emoon** [comment]
Ok.. now it's running and doing stuff!

**Comment by emoon** [comment]
Seems to work fine now.

**Comment by Riateche** [comment]
Great! Check if it works with original version (with "-isystem") with command line tools installed. If not, please submit a PR so that we can see what Travis thinks about it.

**Comment by emoon** [comment]
Seems to work fine without it so all good.
